import {describe,it,expect}from'vitest';import{mkdtemp,readFile,writeFile,stat,symlink}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{Client}from'@modelcontextprotocol/sdk/client/index.js';import{InMemoryTransport}from'@modelcontextprotocol/sdk/inMemory.js';
import{loadConfig}from'../src/config.js';import{GumroadClient,formEncode}from'../src/api/client.js';import {createApp} from '../src/app.js';import {connect as slipwayConnect} from '@thenavidm/slipway/testing';import{ALL_TOOLS}from'../src/tools/index.js';

/** The write policy comes from the environment on Slipway, as it does in use: this is the one a config describes. */
function policy(prefix:string,config:{readOnly?:boolean;allowDestructive?:boolean;auditPath?:string}):Record<string,string>{return{...(config.readOnly?{[`${prefix}_READ_ONLY`]:'1'}:{}),...(config.allowDestructive===false?{[`${prefix}_ALLOW_DESTRUCTIVE`]:'0'}:{}),...(config.auditPath?{[`${prefix}_AUDIT_LOG`]:config.auditPath}:{})};}
/** Slipway's schema check answers in the MCP SDK's own plain text, "Input validation error: …"; these tests read every error as JSON, so it is wrapped as {error}. */
function jsonError(r:any){const text=r.content?.[0]?.text??'';try{JSON.parse(text);return r;}catch{return{...r,content:[{type:'text',text:JSON.stringify({error:text})}]};}}
/** The SDK client's calls these tests were written against, over the real Slipway server. A hidden tool is a protocol error there; it comes back as the error result a client sees. */
function adapt(mcp:Awaited<ReturnType<typeof slipwayConnect>>){return{listTools:async()=>({tools:await mcp.listTools()}),callTool:async({name,arguments:args}:{name:string;arguments?:Record<string,unknown>}):Promise<any>=>{try{const r:any=await mcp.callTool(name,args??{});return r.isError?jsonError(r):r;}catch(e){return{isError:true,content:[{type:'text',text:JSON.stringify({error:(e as Error).message})}]};}},close:()=>mcp.close()};}
/** One tool call through the real server, as the 2.x guard-and-handler helper made it: the result's data, or its error thrown. */
async function viaServer(prefix:string,config:any,client:any,name:string,args:Record<string,unknown>):Promise<any>{const mcp=await slipwayConnect(createApp({context:()=>({config,client})}),{env:policy(prefix,config)});try{const r:any=await mcp.callTool(name,args);const text=(r.content as any[])?.[0]?.text??'';if(r.isError)throw new Error(text);try{return JSON.parse(text);}catch{return text;}}finally{await mcp.close();}}
const env={GUMROAD_ACCESS_TOKEN:'FIXTURE_SELLER',GUMROAD_LICENSE_KEY:'FIXTURE_LICENSE',GUMROAD_MIN_REQUEST_INTERVAL_MS:'0'};
function rig(fn:(u:URL,o:any)=>any=()=>({success:true}),extra:Record<string,string>={}){const seen:{url:URL,opts:any}[]=[];const cfg=loadConfig({...env,...extra});const api=new GumroadClient(cfg,async(u,o)=>{const url=new URL(String(u));seen.push({url,opts:o});const result=await fn(url,o);return result instanceof Response?result:new Response(JSON.stringify(result),{status:200,headers:{'Content-Type':'application/json'}});});return{seen,cfg,api};}
async function app(r:ReturnType<typeof rig>,test:(c:any)=>Promise<void>){const mcp=await slipwayConnect(createApp({context:()=>({config:r.cfg,client:r.api})}),{env:policy('GUMROAD',r.cfg)});try{await test(adapt(mcp));}finally{await mcp.close();}}
async function call(r:ReturnType<typeof rig>,name:string,args:any={}){let out:any;await app(r,async c=>{const v=await c.callTool({name,arguments:args});out={isError:!!v.isError,...JSON.parse((v.content as any)[0].text)};});return out;}
function invoke(name:string,args:any,c:GumroadClient){return ALL_TOOLS.find(t=>t.name===name)!.handler(args,c);}
const tasks=[{tool:'disable_product',arguments:{product_id:'P=='}}];
describe('actual shared discovery and effect policy',()=>{
 it('has57tools,51nativecontracts and all34legacy names',async()=>{const r=rig();await app(r,async c=>{const{tools}=await c.listTools();expect(tools).toHaveLength(57);expect(tools.filter(t=>t.annotations?.readOnlyHint)).toHaveLength(25);expect(tools.filter(t=>t.inputSchema.properties?.confirm)).toHaveLength(32);});expect(r.seen).toHaveLength(0);});
 it.each(['disable_product','refund_sale','increment_license_uses','export_resources'])('requires explicit approval for %s beforefetch',async name=>{const r=rig();const args=name==='disable_product'?{product_id:'P=='}:name==='refund_sale'?{sale_id:'S==',full_refund:true}:name==='increment_license_uses'?{product_id:'P=='}:{operation:'list_sales',output_file:join(tmpdir(),'unused-fixture')};const out=await call(r,name,args);expect(out.isError).toBe(true);expect(JSON.stringify(out)).toContain('confirm');expect(r.seen).toHaveLength(0);});
 it('hides every effect and refuses direct hidden calls with confirm',async()=>{const r=rig(undefined,{GUMROAD_READ_ONLY:'1'});await app(r,async c=>{expect((await c.listTools()).tools).toHaveLength(25);const v=await c.callTool({name:'refund_sale',arguments:{sale_id:'S==',full_refund:true,confirm:true}});expect(v.isError).toBe(true);expect(JSON.stringify(v)).toMatch(/READ_ONLY|not found/);});expect(r.seen).toHaveLength(0);});
 it('global effect disable refuses confirmed writes',async()=>{const r=rig(undefined,{GUMROAD_ALLOW_DESTRUCTIVE:'0'});expect((await call(r,'disable_product',{product_id:'P==',confirm:true})).isError).toBe(true);expect(r.seen).toHaveLength(0);});
 it('unknown fields cannot smuggle seller/license credentials',async()=>{const r=rig();const v=await call(r,'verify_license',{product_id:'P==',license_key:'SMUGGLED'});expect(v.isError).toBe(true);expect(r.seen).toHaveLength(0);});
 it('unknown IDs and traversal are refused beforefetch',async()=>{const r=rig();expect((await call(r,'get_product',{product_id:'../x'})).isError).toBe(true);expect(r.seen).toHaveLength(0);});
});
describe('native request contracts',()=>{
 it('Bearer in header, not URL or body; IDs preserve =padding',async()=>{const r=rig(()=>({success:true,product:{id:'P=='}}));expect((await call(r,'get_product',{product_id:'P=='})).isError).toBe(false);const s=r.seen[0]!;expect(s.url.href).toBe('https://api.gumroad.com/v2/products/P%3D%3D');expect(s.opts.headers.Authorization).toBe('Bearer FIXTURE_SELLER');expect(s.url.search).toBe('');expect(s.opts.redirect).toBe('error');});
 it('verification sendsfalse explicitly without seller auth',async()=>{const r=rig(()=>({success:true,uses:7,purchase:{license_key:'FIXTURE_LICENSE'}}),{GUMROAD_ACCESS_TOKEN:''});const v=await call(r,'verify_license',{product_id:'P=='});expect(v.isError).toBe(false);expect(v.purchase.license_key).toBe('[redacted]');expect(r.seen[0]!.opts.headers.Authorization).toBeUndefined();const form=new URLSearchParams(r.seen[0]!.opts.body);expect(form.get('increment_uses_count')).toBe('false');expect(form.get('license_key')).toBe('FIXTURE_LICENSE');expect(form.get('product_id')).toBe('P==');});
 it('increment uses is separate confirmed native true without OAuth',async()=>{const r=rig(()=>({success:true,uses:8}),{GUMROAD_ACCESS_TOKEN:''});expect((await call(r,'increment_license_uses',{product_id:'P==',confirm:true})).isError).toBe(false);expect(new URLSearchParams(r.seen[0]!.opts.body).get('increment_uses_count')).toBe('true');expect(r.seen[0]!.opts.headers.Authorization).toBeUndefined();});
 it('license mutation requires both intended private credentials',async()=>{const r=rig();await call(r,'disable_license',{product_id:'P==',confirm:true});expect(r.seen[0]!.opts.headers.Authorization).toBe('Bearer FIXTURE_SELLER');expect(new URLSearchParams(r.seen[0]!.opts.body).get('license_key')).toBe('FIXTURE_LICENSE');});
 it('license mutation with no seller credential refuses beforefetch',async()=>{const r=rig(undefined,{GUMROAD_ACCESS_TOKEN:''});expect((await call(r,'disable_license',{product_id:'P==',confirm:true})).isError).toBe(true);expect(r.seen).toHaveLength(0);});
 it('client refuses omitted verify increment flag',async()=>{const r=rig();await expect(r.api.request('POST','/licenses/verify',{product_id:'P=='})).rejects.toThrow('explicit');expect(r.seen).toHaveLength(0);});
 it('nativeform transmitsfalse and repeated arrays',()=>{const f=new URLSearchParams(formEncode({draft:false,tags:['a','b'],variant:{name:'Basic',max_purchase_count:0}}));expect(f.get('draft')).toBe('false');expect(f.getAll('tags[]')).toEqual(['a','b']);expect(f.get('variant[max_purchase_count]')).toBe('0');});
 it('productwrites include only selected real flat fields',async()=>{const r=rig(()=>({success:true,product:{published:true}}));await call(r,'create_product',{name:'Fixture',price:0,draft:false,tags:['a','b'],confirm:true});const f=new URLSearchParams(r.seen[0]!.opts.body);expect(f.get('price')).toBe('0');expect(f.get('draft')).toBe('false');expect(f.getAll('tags[]')).toEqual(['a','b']);expect(f.has('confirm')).toBe(false);});
 it('refund omission cannot become accidental full refund',async()=>{const r=rig();expect((await call(r,'refund_sale',{sale_id:'S==',confirm:true})).isError).toBe(true);expect(r.seen).toHaveLength(0);});
 it('positive partial refund sends native amount_cents',async()=>{const r=rig();await call(r,'refund_sale',{sale_id:'S==',amount_cents:200,confirm:true});expect(new URLSearchParams(r.seen[0]!.opts.body).get('amount_cents')).toBe('200');});
 it('full refund is deliberate local intent, not a native field',async()=>{const r=rig();await call(r,'refund_sale',{sale_id:'S==',full_refund:true,confirm:true});expect(new URLSearchParams(r.seen[0]!.opts.body).has('full_refund')).toBe(false);expect(new URLSearchParams(r.seen[0]!.opts.body).has('amount_cents')).toBe(false);});
 it.each([0,-1,1.5])('refuses invalid amount %s',async amount=>{const r=rig();expect((await call(r,'refund_sale',{sale_id:'S==',amount_cents:amount,confirm:true})).isError).toBe(true);expect(r.seen).toHaveLength(0);});
 it('refuses bothpartial/full',async()=>{const r=rig();expect((await call(r,'refund_sale',{sale_id:'S==',amount_cents:200,full_refund:true,confirm:true})).isError).toBe(true);expect(r.seen).toHaveLength(0);});
 it('subscribers force native paginated=true',async()=>{const r=rig(()=>({success:true,subscribers:[]}));await call(r,'list_subscribers',{product_id:'P=='});expect(r.seen[0]!.url.searchParams.get('paginated')).toBe('true');});
 it('compatibility custom-field get uses only real list endpoint',async()=>{const r=rig(()=>({success:true,custom_fields:[{name:'Phone',required:false}]}));const v=await call(r,'get_custom_field',{product_id:'P==',name:'Phone'});expect(v.custom_field.required).toBe(false);expect(r.seen[0]!.url.pathname).toBe('/v2/products/P%3D%3D/custom_fields');});
 it('custom-field update preservesnativefalse andencodedname',async()=>{const r=rig();await call(r,'update_custom_field',{product_id:'P==',name:'Phone number',required:false,confirm:true});expect(r.seen[0]!.url.pathname).toContain('Phone%20number');expect(new URLSearchParams(r.seen[0]!.opts.body).get('required')).toBe('false');});
 it('webhook creation is PUT with8documented native events',async()=>{const r=rig();await call(r,'create_resource_subscription',{resource_name:'sale',post_url:'https://example.com/hook',confirm:true});expect(r.seen[0]!.opts.method).toBe('PUT');expect(new URLSearchParams(r.seen[0]!.opts.body).get('post_url')).toBe('https://example.com/hook');});
 it('refuses unreviewed event andunsafe callback',async()=>{const r=rig();expect((await call(r,'create_resource_subscription',{resource_name:'deleted_product',post_url:'https://example.com',confirm:true})).isError).toBe(true);expect((await call(r,'create_resource_subscription',{resource_name:'sale',post_url:'http://example.com',confirm:true})).isError).toBe(true);expect(r.seen).toHaveLength(0);});
 it('percentage discounts over100 are refused',async()=>{const r=rig();expect((await call(r,'create_offer_code',{product_id:'P==',name:'X',amount_off:101,offer_type:'percent',confirm:true})).isError).toBe(true);expect(r.seen).toHaveLength(0);});
 it('empty productupdate andconflicting taxonomy refuse',async()=>{const r=rig();expect((await call(r,'update_product',{product_id:'P==',confirm:true})).isError).toBe(true);expect((await call(r,'update_product',{product_id:'P==',category:'design',taxonomy_id:1,confirm:true})).isError).toBe(true);expect(r.seen).toHaveLength(0);});
 it('native HTTP200successfalse is a failure',async()=>{const r=rig(()=>({success:false,message:'Fixture failed'}));expect((await call(r,'get_user')).isError).toBe(true);});
 it('native missing success is not accepted as effectreceipt',async()=>{const r=rig(()=>({ok:true}));expect((await call(r,'disable_product',{product_id:'P==',confirm:true})).isError).toBe(true);});
 it('429 andunknown writes never retry',async()=>{const r=rig(()=>new Response(JSON.stringify({success:false,message:'Limited'}),{status:429}));expect((await call(r,'disable_product',{product_id:'P==',confirm:true})).isError).toBe(true);expect(r.seen).toHaveLength(1);});
 it('redacts errors containing configuredsecrets andsignedURL',async()=>{const r=rig(()=>({success:false,message:'FIXTURE_SELLER FIXTURE_LICENSE https://x.com/a?access_token=hidden'}));const v=await call(r,'get_user');const s=JSON.stringify(v);expect(s).not.toContain('FIXTURE_SELLER');expect(s).not.toContain('FIXTURE_LICENSE');expect(s).not.toContain('access_token=hidden');});
});
describe('isolated private profiles andfiles',()=>{
 it('namedlicenseprofile neverfallsback globalseller',async()=>{const r=rig(undefined,{GUMROAD_ACCOUNTS:JSON.stringify([{name:'license',license_key:'PROFILE_LICENSE'}])});expect((await call(r,'get_user',{account:'license'})).isError).toBe(true);expect(r.seen).toHaveLength(0);});
 it('exactprofilechoice usesintendedseller',async()=>{const r=rig(undefined,{GUMROAD_ACCOUNTS:JSON.stringify([{name:'one',access_token:'ONE'},{name:'two',access_token:'TWO'}])});await call(r,'get_user',{account:'two'});expect(r.seen[0]!.opts.headers.Authorization).toBe('Bearer TWO');});
 it('unknownprofile refuses',async()=>{const r=rig();expect((await call(r,'get_user',{account:'wrong'})).isError).toBe(true);expect(r.seen).toHaveLength(0);});
 it('duplicateprofiles andmixedsources refuse',()=>{expect(()=>loadConfig({GUMROAD_ACCOUNTS:'[{"name":"x"},{"name":"x"}]'})).toThrow('unique');expect(()=>loadConfig({GUMROAD_ACCOUNTS:'[{"name":"x","access_token":"A","token_file":"/tmp/b"}]'})).toThrow('one private');});
 it('private owner-onlyfile loadsandredacts token',async()=>{const d=await mkdtemp(join(tmpdir(),'gumroad-test-'));const file=join(d,'token');await writeFile(file,'FILE_FIXTURE',{mode:0o600});const r=rig(()=>({success:true,access_token:'FILE_FIXTURE'}),{GUMROAD_ACCESS_TOKEN:'',GUMROAD_TOKEN_FILE:file});const v=await call(r,'get_user');expect(r.seen[0]!.opts.headers.Authorization).toBe('Bearer FILE_FIXTURE');expect(v.access_token).toBe('[redacted]');});
 it('symlinktoken rejectedbeforefetch',async()=>{const d=await mkdtemp(join(tmpdir(),'gumroad-test-'));await writeFile(join(d,'key'),'FIXTURE',{mode:0o600});try{await symlink(join(d,'key'),join(d,'link'));}catch(e){if(process.platform==='win32')return;throw e;}const r=rig(undefined,{GUMROAD_ACCESS_TOKEN:'',GUMROAD_TOKEN_FILE:join(d,'link')});expect((await call(r,'get_user')).isError).toBe(true);expect(r.seen).toHaveLength(0);});
 it('rotatedlicense goesonlyto newprivate file',async()=>{const d=await mkdtemp(join(tmpdir(),'gumroad-test-')),file=join(d,'rotated.json');const r=rig(()=>({success:true,purchase:{license_key:'REPLACEMENT_FIXTURE'}}));const v=await call(r,'rotate_license',{product_id:'P==',output_file:file,confirm:true});expect(v.saved).toBe(true);expect(JSON.stringify(v)).not.toContain('REPLACEMENT_FIXTURE');expect(JSON.parse(await readFile(file,'utf8')).purchase.license_key).toBe('REPLACEMENT_FIXTURE');if(process.platform!=='win32')expect((await stat(file)).mode&0o777).toBe(0o600);});
 it('existing rotatedoutput refuses beforeeffect',async()=>{const d=await mkdtemp(join(tmpdir(),'gumroad-test-')),file=join(d,'kept');await writeFile(file,'KEEP');const r=rig();expect((await call(r,'rotate_license',{product_id:'P==',output_file:file,confirm:true})).isError).toBe(true);expect(await readFile(file,'utf8')).toBe('KEEP');expect(r.seen).toHaveLength(0);});
});
describe('reviewedbatches andbounded exports',()=>{
 it('previewis local andhash excludesprivatecredentials',async()=>{const r=rig();const v=await call(r,'preview_commerce_batch',{tasks});expect(v.localOnly).toBe(true);expect(v.reviewSha256).toMatch(/^[a-f0-9]{64}$/);expect(r.seen).toHaveLength(0);expect(JSON.stringify(v)).not.toContain('FIXTURE_SELLER');});
 it('wronghash andinvalidlater task refusebeforefirstrequest',async()=>{const r=rig();expect((await call(r,'submit_commerce_batch',{tasks,review_sha256:'0'.repeat(64),confirm:true})).isError).toBe(true);expect((await call(r,'preview_commerce_batch',{tasks:[...tasks,{tool:'refund_sale',arguments:{sale_id:'S=='}}]})).isError).toBe(true);expect(r.seen).toHaveLength(0);});
 it('changedorder orprofile invalidatesreview',async()=>{const r=rig(undefined,{GUMROAD_ACCOUNTS:'[{"name":"a","access_token":"A"},{"name":"b","access_token":"B"}]'});const v=await call(r,'preview_commerce_batch',{tasks,account:'a'});expect((await call(r,'submit_commerce_batch',{tasks,account:'b',review_sha256:v.reviewSha256,confirm:true})).isError).toBe(true);expect(r.seen).toHaveLength(0);});
 it('batchstopsfirst failure withknown/unattemptedindices',async()=>{let count=0;const r=rig(()=>++count===2?{success:false,message:'Uncertain fixture'}:{success:true});const tasks=[{tool:'disable_product',arguments:{product_id:'P1=='}},{tool:'disable_product',arguments:{product_id:'P2=='}},{tool:'disable_product',arguments:{product_id:'P3=='}}];const v=await call(r,'preview_commerce_batch',{tasks});const out=await call(r,'submit_commerce_batch',{tasks,review_sha256:v.reviewSha256,confirm:true});expect(out.error).toBeTruthy();const detail=JSON.parse(out.error);expect(detail.knownResults).toHaveLength(1);expect(detail.failedIndex).toBe(1);expect(detail.unattemptedIndices).toEqual([2]);expect(r.seen).toHaveLength(2);});
 it('export budgets retainpartialpage cursorand offset',async()=>{const d=await mkdtemp(join(tmpdir(),'gumroad-test-'));const r=rig(()=>({success:true,sales:[{id:'1',license_key:'PRIVATE'},{id:'2'}],next_page_key:'NEXT',next_page_url:'https://malicious.invalid/'}));const v=await call(r,'export_resources',{operation:'list_sales',max_items:1,output_file:join(d,'sales'),confirm:true});expect(v.items).toBe(1);expect(v.continuation.start_offset).toBe(1);expect(r.seen).toHaveLength(1);expect(JSON.parse(await readFile(join(d,'sales'),'utf8')).data[0].license_key).toBe('[redacted]');});
 it('followscursor atfixedhost andnevernativeURL',async()=>{const d=await mkdtemp(join(tmpdir(),'gumroad-test-'));const r=rig(u=>u.searchParams.get('page_key')==='NEXT'?{success:true,sales:[{id:'2'}]}:{success:true,sales:[{id:'1'}],next_page_key:'NEXT',next_page_url:'https://malicious.invalid/'});const v=await call(r,'export_resources',{operation:'list_sales',output_file:join(d,'sales'),confirm:true});expect(v.items).toBe(2);expect(v.completeWithinRequestedFilters).toBe(true);expect(r.seen.every(s=>s.url.hostname==='api.gumroad.com')).toBe(true);});
 it('exportpagebudget exposes nextcursor',async()=>{const d=await mkdtemp(join(tmpdir(),'gumroad-test-'));const r=rig(()=>({success:true,products:[{id:'1'}],next_page_key:'NEXT'}));const v=await call(r,'export_resources',{operation:'list_products',max_pages:1,output_file:join(d,'products'),confirm:true});expect(v.continuation.arguments.page_key).toBe('NEXT');expect(v.continuation.start_offset).toBe(0);});
 it('subscribers exportforces nativepagination',async()=>{const d=await mkdtemp(join(tmpdir(),'gumroad-test-'));const r=rig(()=>({success:true,subscribers:[]}));await call(r,'export_resources',{operation:'list_subscribers',arguments:{product_id:'P=='},output_file:join(d,'sub'),confirm:true});expect(r.seen[0]!.url.searchParams.get('paginated')).toBe('true');});
 it('unsafeURL-only continuationremovesonly newpartialfile',async()=>{const d=await mkdtemp(join(tmpdir(),'gumroad-test-'));const r=rig(()=>({success:true,sales:[{id:'1'}],next_page_url:'https://malicious.invalid/'}));expect((await call(r,'export_resources',{operation:'list_sales',output_file:join(d,'new'),confirm:true})).isError).toBe(true);await expect(stat(join(d,'new'))).rejects.toThrow();});
 it('exportexistingfile neverfetches oroverwrites',async()=>{const d=await mkdtemp(join(tmpdir(),'gumroad-test-')),file=join(d,'kept');await writeFile(file,'KEEP');const r=rig();expect((await call(r,'export_resources',{operation:'list_sales',output_file:file,confirm:true})).isError).toBe(true);expect(r.seen).toHaveLength(0);expect(await readFile(file,'utf8')).toBe('KEEP');});
 it('export refuses cursor cycles including initial cursor',async()=>{const d=await mkdtemp(join(tmpdir(),'gumroad-test-'));const r=rig(u=>({success:true,sales:[{id:'1'}],next_page_key:u.searchParams.get('page_key')==='FIRST'?'SECOND':'FIRST'}));expect((await call(r,'export_resources',{operation:'list_sales',arguments:{page_key:'FIRST'},output_file:join(d,'cycle'),confirm:true})).isError).toBe(true);expect(r.seen).toHaveLength(2);await expect(stat(join(d,'cycle'))).rejects.toThrow();});
 it('local schemas andprofile list makezero nativecalls',async()=>{const r=rig();expect((await call(r,'get_operation_schema',{operation:'refund_sale'})).operation.scope).toBe('edit_sales');expect((await call(r,'list_accounts')).accounts[0].sellerConfigured).toBe(true);expect(r.seen).toHaveLength(0);});
});
