import{open,lstat}from'node:fs/promises';import{constants}from'node:fs';import{isAbsolute}from'node:path';
import{selectAccount,type Account,type Config}from'../config.js';import{GumroadError,UsageError}from'./errors.js';import operations from'../tools/operations.json'with{type:'json'};
export type Json=Record<string,any>;const MAX=5*1048576;
const routes=operations.map(o=>({method:o.method,regex:new RegExp('^'+o.path.replace(/[.*+?^$()|[\]\\]/g,'\\$&').replace(/\{[^}]+\}/g,'([^/]+)')+'$')}));
export function formEncode(body:Json):string{const form=new URLSearchParams();function add(key:string,value:any){if(value===undefined||value===null)return;if(Array.isArray(value)){for(const item of value)add(key+'[]',item);}else if(typeof value==='object'){for(const [k,v]of Object.entries(value))add(key+'['+k+']',v);}else form.append(key,String(value));}for(const [k,v]of Object.entries(body))add(k,v);return form.toString();}
export class GumroadClient{
 private tokens=new Map<string,string>();private schedule:Promise<void>=Promise.resolve();private nextAt=0;
 constructor(readonly config:Config,private readonly fetcher:typeof fetch=fetch,private readonly sleep:(ms:number)=>Promise<void>=ms=>new Promise(r=>setTimeout(r,ms))){}
 redactText(text:string){for(const secret of [...this.config.accounts.flatMap(a=>[a.apiToken,a.licenseKey]),...this.tokens.values()].filter(Boolean).sort((a,b)=>b.length-a.length))text=text.split(secret).join('[redacted]');return text.replace(/https?:\/\/[^\s"<>]*(?:X-Amz-Signature|[?&](?:token|signature|sig|key|access_token)=)[^\s"<>]*/gi,'[private credential URL]');}
 sanitize(v:unknown):unknown{if(typeof v==='string')return this.redactText(v);if(Array.isArray(v))return v.map(x=>this.sanitize(x));if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,/^(password|secret|api_key|license_key|licenseKey|signing_key|api_token|token|access_token|refresh_token|authorization|client_secret|download_url|content_url|signed_url)$/i.test(k)?'[redacted]':this.sanitize(x)]));return v;}
 private async credential(a:Account,license=false){const label=a.name+':'+(license?'license':'api');if(this.tokens.has(label))return this.tokens.get(label)!;let token=license?a.licenseKey:a.apiToken;const path=license?a.licenseFile:a.tokenFile;if(path){let f;try{if(!isAbsolute(path)||(await lstat(path)).isSymbolicLink())throw Error();f=await open(path,constants.O_RDONLY|(constants.O_NOFOLLOW??0));const stat=await f.stat();if(!stat.isFile()||stat.size>65536||(process.platform!=='win32'&&((stat.mode&0o077)||stat.uid!==process.getuid?.())))throw Error();token=(await f.readFile('utf8')).trim();}catch{throw new GumroadError('Cannot read the selected private credential file; use an absolute owner-only regular token-only file at most64KiB.',0,'CONFIG');}finally{await f?.close();}}if(!token||/[\r\n]/.test(token))throw new GumroadError('No valid '+(license?'license credential':'seller access token')+' configured for the selected profile. Run gumroad-cli login.',0,'CONFIG');this.tokens.set(label,token);return token;}
 private async pace(){const next=this.schedule.catch(()=>{}).then(async()=>{const delay=Math.max(0,this.nextAt-Date.now());if(delay)await this.sleep(delay);this.nextAt=Date.now()+this.config.minIntervalMs;});this.schedule=next;await next;}
 private async bytes(response:Response){const chunks:Uint8Array[]=[];let total=0;const reader=response.body?.getReader();if(reader)try{for(;;){const part=await reader.read();if(part.done)break;total+=part.value.byteLength;if(total>MAX){await reader.cancel();throw new GumroadError('Response exceeds the5MiB local cap; no automatic retry.');}chunks.push(part.value);}}finally{reader.releaseLock();}return Buffer.concat(chunks);}
 async request(method:string,path:string,fields:Json={},hint?:string):Promise<any>{
  if(!routes.some(r=>r.method===method&&r.regex.test(path))||/[?#\\]/.test(path)||/%2f|%5c|%00/i.test(path)||path.split('/').some(s=>['.','..'].includes(decodeURIComponent(s))))throw new UsageError('Unsupported Gumroad API method or path.');
  if(Object.keys(fields).some(k=>/^(access_token|authorization|license_key)$/i.test(k)))throw new UsageError('Credentials are private configuration, never request arguments.');
  const a=selectAccount(this.config,hint),license=path.startsWith('/licenses/'),verify=path==='/licenses/verify';
  if(verify&&typeof fields.increment_uses_count!=='boolean')throw new UsageError('License verify requires an explicit increment_uses_count boolean; omission is unsafe.');
  const body={...fields};if(license)body.license_key=await this.credential(a,true);
  const headers:Record<string,string>={Accept:'application/json','User-Agent':'Navid Media Gumroad MCP CLI/2.0.0 (https://navid.me)'};if(!verify)headers.Authorization='Bearer '+await this.credential(a);
  const url=new URL('/v2'+path,'https://api.gumroad.com');let encoded:string|undefined;
  if(method==='GET'){for(const[k,v]of Object.entries(body)){if(v===undefined)continue;if(typeof v==='object')throw new UsageError('Unsupported object or array query field.');url.searchParams.set(k,String(v));}}else{headers['Content-Type']='application/x-www-form-urlencoded';encoded=formEncode(body);if(Buffer.byteLength(encoded)>1048576)throw new UsageError('Request exceeds the1MiB local cap.');}
  await this.pace();let response:Response;try{response=await this.fetcher(url,{method,redirect:'error',signal:AbortSignal.timeout(this.config.timeoutMs),headers,...(encoded===undefined?{}:{body:encoded})});}catch{throw new GumroadError('Request failed or timed out. Outcome may be unknown; no automatic retry. Inspect provider state before deliberately repeating.',0,'NETWORK');}
  const bytes=await this.bytes(response);let parsed;try{parsed=JSON.parse(bytes.toString('utf8'));}catch{throw new GumroadError('Provider returned a missing or non-JSON receipt; no automatic retry.',response.status);}
  if(!response.ok||parsed?.success===false){const message=this.redactText(String(parsed?.message??parsed?.error??'Native request failed')).slice(0,1000);throw new GumroadError('Gumroad API '+response.status+': '+message,response.status,response.status===429?'RATE_LIMIT':response.status===404?'NOT_FOUND':[401,403].includes(response.status)?'AUTH':'API_ERROR');}
  if(!parsed||typeof parsed!=='object'||Array.isArray(parsed)||parsed.success!==true)throw new GumroadError('Invalid native success receipt; requested effect outcome may be unknown.');return parsed;
 }
}
