export type Account={name:string;apiToken:string;tokenFile:string;licenseKey:string;licenseFile:string};
export type Config={accounts:Account[];defaultAccount:string;readOnly:boolean;allowDestructive:boolean;auditPath:string;timeoutMs:number;minIntervalMs:number};
function integer(v:string|undefined,fallback:number,min:number,max:number){const n=v?Number(v):fallback;if(!Number.isInteger(n)||n<min||n>max)throw Error('Invalid request timeout or pacing settings.');return n;}
export function loadConfig(env:NodeJS.ProcessEnv=process.env):Config{
 let entries:Record<string,unknown>[]=[];
 if(env.GUMROAD_ACCOUNTS){try{const v=JSON.parse(env.GUMROAD_ACCOUNTS);if(!Array.isArray(v))throw Error();entries=v;}catch{throw Error('GUMROAD_ACCOUNTS must be a private JSON array of named profiles.');}}
 else if(env.GUMROAD_ACCESS_TOKEN||env.GUMROAD_TOKEN_FILE||env.GUMROAD_LICENSE_KEY||env.GUMROAD_LICENSE_FILE)entries=[{name:'default',access_token:env.GUMROAD_ACCESS_TOKEN,token_file:env.GUMROAD_TOKEN_FILE,license_key:env.GUMROAD_LICENSE_KEY,license_file:env.GUMROAD_LICENSE_FILE}];
 const accounts=entries.map(x=>{if(!x||typeof x!=='object'||typeof x.name!=='string'||!x.name.trim())throw Error('Every Gumroad profile requires a nonempty name.');for(const k of ['access_token','token_file','license_key','license_file'])if(x[k]!==undefined&&(typeof x[k]!=='string'||/[\r\n]/.test(x[k] as string)))throw Error('Private profile settings must be strings without line breaks.');if(x.access_token&&x.token_file||x.license_key&&x.license_file)throw Error('Select one private source per credential type.');if(Object.keys(x).some(k=>!['name','access_token','token_file','license_key','license_file'].includes(k)))throw Error('Unsupported private profile setting.');return{name:x.name.trim(),apiToken:String(x.access_token??''),tokenFile:String(x.token_file??''),licenseKey:String(x.license_key??''),licenseFile:String(x.license_file??'')};});
 if(new Set(accounts.map(a=>a.name)).size!==accounts.length)throw Error('Profile names must be unique.');const defaultAccount=env.GUMROAD_DEFAULT_ACCOUNT??accounts[0]?.name??'';if(defaultAccount&&!accounts.some(a=>a.name===defaultAccount))throw Error('Unknown GUMROAD_DEFAULT_ACCOUNT.');
 return{accounts,defaultAccount,readOnly:/^(1|true)$/i.test(env.GUMROAD_READ_ONLY??''),allowDestructive:!/^(0|false)$/i.test(env.GUMROAD_ALLOW_DESTRUCTIVE??''),auditPath:env.GUMROAD_AUDIT_LOG??'',timeoutMs:integer(env.GUMROAD_REQUEST_TIMEOUT_MS,30000,100,300000),minIntervalMs:integer(env.GUMROAD_MIN_REQUEST_INTERVAL_MS,1000,0,10000)};
}
export function selectAccount(c:Config,hint?:string):Account{const a=c.accounts.find(a=>a.name===(hint??c.defaultAccount));if(!a)throw Error(c.accounts.length?'Unknown profile; run list_accounts and use its exact label.':'No credentials configured. Set GUMROAD_ACCESS_TOKEN or GUMROAD_LICENSE_FILE privately; run gumroad-cli login.');return a;}
