import operationsData from'./operations.json'with{type:'json'};import provenance from'./provenance.json'with{type:'json'};import{Ajv,type ValidateFunction}from'ajv';import addFormats from'ajv-formats';import{open,unlink}from'node:fs/promises';import{isAbsolute}from'node:path';import{createHash}from'node:crypto';
import{GumroadClient,type Json}from'../api/client.js';import{GumroadError,UsageError}from'../api/errors.js';import{selectAccount,type Config}from'../config.js';import type { Risk } from "@thenavidm/slipway";
export type Operation={name:string;title:string;description:string;method:string;path:string;group:string;risk:Risk;pathKeys:Record<string,string>;properties:Json;required:string[];nativeFields:string[];scope:string;licenseAPI:boolean;privateOutput:boolean;collection:string|null;sourceFile:string};
export type ToolSpec={name:string;title:string;description:string;group:string;inputSchema:Json;risk:Risk;handler:(args:Json,client:GumroadClient)=>Promise<unknown>};
const operations=operationsData as unknown as Operation[];const ajv=new Ajv({allErrors:true,strict:false});(addFormats as unknown as(a:Ajv)=>void)(ajv);
const account={type:'string',description:'Exact private profile label; never inherited credentials, ownership or scope proof.'};const confirm={type:'boolean',description:'Explicit approval of this exact native effect or private file output.'};
function fieldsFor(op:Operation){return{type:'object',properties:{...op.properties,account,...(op.risk!=='read'?{confirm}:{}),...(op.privateOutput?{output_file:{type:'string',minLength:1,description:'Required absolute NEW owner-private file for the replacement license receipt; no overwrite.'}}:{})},required:[...op.required,...(op.privateOutput?['output_file']:[])],additionalProperties:false};}
function prepare(op:Operation,args:Json){
 const fields=Object.fromEntries(op.nativeFields.filter(k=>args[k]!==undefined).map(k=>[k,args[k]]));
 if(op.name==='verify_license')fields.increment_uses_count=false;if(op.name==='increment_license_uses')fields.increment_uses_count=true;if(op.name==='list_subscribers')fields.paginated=true;
 if(op.name==='refund_sale'){if(args.full_refund===true&&args.amount_cents!==undefined)throw new UsageError('Choose amount_cents or explicit full_refund, not both.');if(args.amount_cents===undefined&&args.full_refund!==true)throw new UsageError('Refund requires positive amount_cents or explicit full_refund: true. Omission alone must never mean full refund.');}
 if(op.name==='create_offer_code'&&(args.offer_type??'cents')==='percent'&&(args.amount_off<1||args.amount_off>100))throw new UsageError('Percentage amount_off must be between1and100.');
 if(op.name.startsWith('update_')&&!Object.keys(fields).length)throw new UsageError('Update requires at least one native field.');
 if(args.category!==undefined&&args.taxonomy_id!==undefined)throw new UsageError('Use category or taxonomy_id, not both.');
 if(args.after&&args.before&&args.after>args.before)throw new UsageError('after must not follow before.');
 if(args.draft===true&&args.published===true)throw new UsageError('Contradictory draft and published flags.');
 if(args.refund_period==='inherit'&&args.refund_fine_print!==undefined)throw new UsageError('Inherited refund policy cannot have product fine print.');
 for(const key of['post_url','tracking_url'])if(args[key]){const u=new URL(args[key]);if(u.protocol!=='https:'||u.username||u.password)throw new UsageError('Callbacks/tracking must use HTTPS without embedded credentials.');}
 const path=Object.entries(op.pathKeys).reduce((s,[native,key])=>s.replace('{'+native+'}',encodeURIComponent(String(args[key]))),op.path);return{method:op.method,path,fields};
}
async function savePrivate(path:string,value:unknown){if(!isAbsolute(path))throw new UsageError('output_file must be absolute.');let f;try{f=await open(path,'wx',0o600);}catch{throw new UsageError('Cannot exclusively create output_file; never overwrites or follows a target symlink.');}try{const actual=typeof value==='function'?await(value as()=>Promise<unknown>)():value;const bytes=Buffer.from(JSON.stringify(actual)+'\n');if(bytes.length>5*1048576)throw new UsageError('Private output exceeds the5MiB local cap.');await f.writeFile(bytes);return{saved:true,output_file:path,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')};}catch(e){await f.close();f=undefined;await unlink(path).catch(()=>{});throw e;}finally{await f?.close();}}
async function execute(op:Operation,args:Json,c:GumroadClient){const call=prepare(op,args);const run=()=>c.request(call.method,call.path,call.fields,args.account);return op.privateOutput?savePrivate(args.output_file,run):c.sanitize(await run());}
export const ALL_TOOLS:ToolSpec[]=operations.map(op=>({...op,inputSchema:fieldsFor(op),handler:(args,c)=>execute(op,args,c)}));
function helper(name:string,title:string,description:string,risk:Risk,properties:Json,required:string[],handler:ToolSpec['handler']){ALL_TOOLS.push({name,title,description,group:'local_workflows',risk,inputSchema:{type:'object',properties,required,additionalProperties:false},handler});}
helper('get_custom_field','Get exact custom checkout field','Compatibility read using documented list_custom_fields then exact field-name match. There is no native single-custom-field GET endpoint.','read',{product_id:{type:'string',pattern:'^[A-Za-z0-9_=-]+$',minLength:1,maxLength:256},name:{type:'string',minLength:1,maxLength:256},account},['product_id','name'],async(a,c)=>{const r=await c.request('GET','/products/'+encodeURIComponent(a.product_id)+'/custom_fields',{},a.account);if(!Array.isArray(r.custom_fields))throw new GumroadError('Invalid native custom_fields receipt.');const row=r.custom_fields.find((x:Json)=>x.name===a.name);if(!row)throw new GumroadError('Custom field not found.',404,'NOT_FOUND');return{success:true,custom_field:c.sanitize(row)};});
helper('list_accounts','List configured accounts','Local profile labels/default and credential availability only. No secrets, file paths, provider identity or network.','read',{},[],async(_,c)=>({accounts:c.config.accounts.map(a=>({name:a.name,default:a.name===c.config.defaultAccount,sellerConfigured:!!(a.apiToken||a.tokenFile),licenseConfigured:!!(a.licenseKey||a.licenseFile)}))}));
helper('get_operation_schema','Inspect reviewed native contract','Local native method/path, fields, scopes and pinned provenance. Field subset, not an official OpenAPI document or permission proof.','read',{operation:{type:'string',enum:operations.map(o=>o.name)}},['operation'],async a=>({operation:operations.find(o=>o.name===a.operation),source:provenance.source,sourceSha:provenance.sourceSha,checked:provenance.checked,snapshotSha256:provenance.sanitizedSnapshotSha256}));
const allowed=operations.filter(o=>o.risk!=='read'&&!o.privateOutput).map(o=>o.name);
const tasks={type:'array',minItems:1,maxItems:20,description:'One to twenty exact ordered native effects. No replacement-key output. Nested arguments cannot override profile/confirmation or carry credentials/files.',items:{type:'object',properties:{tool:{type:'string',enum:allowed},arguments:{type:'object'}},required:['tool','arguments'],additionalProperties:false}};
function canonical(v:any):any{if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));return v;}
function hash(v:any){return createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');}
function reviewed(args:Json,c:GumroadClient){const selected=selectAccount(c.config,args.account);const calls=[];for(const task of args.tasks){if(!allowed.includes(task.tool))throw new UsageError('Unsupported batch tool.');if(['account','confirm','license_key','access_token','output_file'].some(k=>task.arguments[k]!==undefined))throw new UsageError('Batch arguments cannot override profile/confirmation or carry credentials/output files.');const t=ALL_TOOLS.find(t=>t.name===task.tool)!,op=operations.find(o=>o.name===task.tool)!;validateArguments(t,task.arguments);calls.push(prepare(op,task.arguments));}return{version:1,profile:selected.name,credentialBinding:'profile label only; private credentials not hashed',snapshotSha256:provenance.sanitizedSnapshotSha256,tasks:args.tasks,calls};}
helper('preview_commerce_batch','Review exact ordered effects','Local validation/hash binding exact ordered requests/profile label/native snapshot. No provider requests, secret loading, ownership/state validation or financial guarantee.','read',{tasks,account},['tasks'],async(a,c)=>{const r=reviewed(a,c);return{...c.sanitize(r)as Json,reviewSha256:hash(r),localOnly:true,providerValidated:false,notice:'Local request binding, not a provider approval token. No expiry, single-use guarantee, credential fingerprint, state lock, transaction or rollback. Re-review after credential/provider changes.'};});
helper('submit_commerce_batch','Execute exact reviewed effects','Confirmed ordered native effects, all prevalidated before first request, exact hash checked, stops first failure with known/unattempted receipts. No retry or implicit continuation.','destructive',{tasks,account,confirm,review_sha256:{type:'string',pattern:'^[a-f0-9]{64}$'}},['tasks','review_sha256'],async(a,c)=>{const r=reviewed(a,c);if(hash(r)!==a.review_sha256)throw new UsageError('Review hash mismatch; preview the identical tasks/profile/schema again.');const knownResults:Json[]=[];for(let i=0;i<r.calls.length;i++){const call=r.calls[i]!;try{knownResults.push({index:i,tool:a.tasks[i].tool,result:c.sanitize(await c.request(call.method,call.path,call.fields,r.profile))});}catch(e){const err=e as GumroadError;throw new GumroadError(JSON.stringify(c.sanitize({notice:'Batch stopped. Failed request outcome may be unknown; inspect native state before repeating. No retries or rollback.',knownResults,failedIndex:i,unattemptedIndices:r.calls.slice(i+1).map((_,j)=>i+1+j),error:err.message})),err.status??0,err.code??'API_ERROR');}}return{requestsProcessed:true,knownResults,notice:'Native receipts are not independent settlement or customer delivery proof.'};});
const lists=operations.filter(o=>o.collection);
helper('export_resources','Export bounded private metadata','Confirmed cursor-based JSON export into a new exclusive0600 private file, with page/item/byte budgets and explicit continuation. No URL following, digital files or atomic backup.','destructive',{operation:{type:'string',enum:lists.map(o=>o.name)},arguments:{type:'object',description:'Actual list filters/page_key, no account override.'},account,confirm,start_offset:{type:'integer',minimum:0,maximum:9999},max_pages:{type:'integer',minimum:1,maximum:100},max_items:{type:'integer',minimum:1,maximum:10000},output_file:{type:'string',minLength:1}},['operation','output_file'],async(a,c)=>{
 const op=lists.find(o=>o.name===a.operation)!,args=a.arguments??{};if(args.account!==undefined)throw new UsageError('Export arguments cannot override profile.');validateArguments(ALL_TOOLS.find(t=>t.name===op.name)!,args);let receipt:Json={};const saved=await savePrivate(a.output_file,async()=>{
 const maxPages=a.max_pages??10,maxItems=a.max_items??1000;let cursor=args.page_key,offset=a.start_offset??0,requests=0,complete=false;const data:Json[]=[];const seen=new Set<string>();if(cursor!==undefined)seen.add(cursor);
 while(requests<maxPages&&data.length<maxItems){const call=prepare(op,{...args,...(cursor===undefined?{}:{page_key:cursor})});const result=await c.request(call.method,call.path,call.fields,a.account);requests++;const rows=result[op.collection!];if(!Array.isArray(rows)||rows.length>10000)throw new GumroadError('Invalid native collection receipt.');if(offset>rows.length)throw new UsageError('Resume page changed; offset no longer exists.');const take=Math.min(rows.length-offset,maxItems-data.length);data.push(...rows.slice(offset,offset+take));offset+=take;if(offset<rows.length)break;const next=result.next_page_key;if(next===undefined||next===null||next===''){if(result.next_page_url)throw new GumroadError('Next-page URL without a safe native cursor; cannot establish completeness.');complete=true;break;}if(typeof next!=='string'||next.length>1024||!next||next===cursor||seen.has(next)||!rows.length)throw new GumroadError('Invalid/repeated native continuation cursor; export stopped.');seen.add(next);cursor=next;offset=0;if(Buffer.byteLength(JSON.stringify(data))>5*1048576)throw new GumroadError('Export exceeds the5MiB local cap.');}
 receipt={requests,items:data.length,completeWithinRequestedFilters:complete,continuation:complete?null:{operation:op.name,arguments:{...args,...(cursor===undefined?{}:{page_key:cursor})},start_offset:offset},atomicSnapshot:false,credentialsAndSignedURLsRedacted:true};return{data:c.sanitize(data),receipt};});return{...saved,...receipt};
});

// Each schema compiles on first use: compiling all of them at load held back the server's first answer. compileAll() runs them in tests.
const validators=new Map<string,ValidateFunction>();function validatorFor(tool:ToolSpec):ValidateFunction{let v=validators.get(tool.name);if(!v){v=ajv.compile(tool.inputSchema);validators.set(tool.name,v);}return v;}
/** Compile every input schema, as loading once did, so a test can prove they all compile. */
export function compileAll():number{for(const t of ALL_TOOLS)validatorFor(t);return validators.size;}
export function validateArguments(tool:ToolSpec,args:Json){const v=validatorFor(tool);if(!v(args))throw new UsageError(ajv.errorsText(v.errors,{separator:'; '}));}export function visibleTools(c:Config){return ALL_TOOLS.filter(t=>!c.readOnly||t.risk==='read');}
